### ISSUE TITLE
[Sugerencia] Uso del operador "Nullish Coalescing"

### ISSUE THREAD

**Issue by Shompi** [normal-project/Normal#16]
https://github.com/normal-project/Normal/blob/9bee19ad928f106a6bcd0eadd2300587c71ed951/src/commands/utility/avatar.ts#L55

Desde node v14 con la existencia del operador ?? (Nullish coalescing operator) esto puede ser facilmente cambiado a
`user.avatarURL({format:'png', size:1024, dynamic: true}) ?? wtf`, en este caso, `wtf` solo será usado si el lado izquierdo del operador es `null` o `undefined`

Lo mismo puede aplicarse aqui
https://github.com/normal-project/Normal/blob/master/src/commands/utility/avatar.ts#L42

**Comment by gatomo-oficial** [comment]
@Shompi muchas gracias por tu sugerencia, no era consciente de la existencia de ese operador. Lo aplicaré en el próximo commit (en el cual incluiré el sistema de sugerencias) 😁
Si quieres, puedes unirte al server de soporte para mantenerte informado/a del desarrollo
